### ISSUE TITLE
Error when run MNIST: await inputVideoFrame.CopyToAsync(cropped_vf, cropBounds, null);

### ISSUE THREAD

**Issue by tja2000** [Microsoft/Windows-Machine-Learning#10] opened 2018-04-12 19:22 UTC
The app builds and deploys, when submitting the picture I get:

![image](https://user-images.githubusercontent.com/11030714/38699099-6863caae-3e97-11e8-8b01-22803b212330.png)

Running on:
![image](https://user-images.githubusercontent.com/11030714/38699105-702e9412-3e97-11e8-8016-64c529a8a698.png)

VS:
![image](https://user-images.githubusercontent.com/11030714/38699145-825de250-3e97-11e8-8a06-c08b90a20106.png)

**Comment by tja2000** [comment] 2018-04-16 09:55
bump.

**Comment by LPBourret** [comment] 2018-04-17 18:28
Hi,
I could not reproduce your error on a VM running the same build (17127.1) using the same SDK (17125), is there something special about your VM configuration? This kind of error not expected when using an API, unless the project is using a different .winmd then the one shipped with the SDK.

**Comment by tja2000** [comment] 2018-04-17 18:57
I used the Azure Win 10 VM and activated the the 'dev' options so I could install the correct version of the OS. How can I check this winmd?

**Comment by LPBourret** [comment] 2018-04-17 20:53
in your project properties, can you confirm the target version is 17125, and that you are compiling the [demo project](https://github.com/Microsoft/Windows-Machine-Learning/tree/master/Samples/UWP/MNIST/src) as is without modifications

**Comment by tja2000** [comment] 2018-04-18 06:07
I am using the default code coming from github.
![image](https://user-images.githubusercontent.com/11030714/38914417-90c86c74-42df-11e8-8d8e-efa2764af616.png)

**Comment by walrusmcd** [comment] 2018-08-14 20:26
Hello !   Closing this issue, this was against the Preview api and we are now shipping the non-preview API .  Please reactivate if it is occurring in the current windows insider builds and converters, we would love to help !

**Closed by walrusmcd** 2018-08-14 20:26 UTC
