### ISSUE TITLE
Class not registered?

### ISSUE THREAD

**Issue by donaparker01** [microsoft/Windows-Machine-Learning#244] opened 2019-06-12 22:31 UTC
I receive the following error after trying to run resnet50 using winML. 

Loading model (path = resnet50\resnet50\model.onnx)...
Load Model: resnet50\resnet50\model.onnx [FAILED]
Class not registered
Class not registered

Systems
Processor:	Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz, 1896 Mhz, 4 Core(s), 8 Logical Processor(s)
OS:  Microsoft Windows 10 Enterprise

**Comment by ryanlai2** [comment] 2019-06-12 23:03
Hi @donaparker01 , thanks for reaching out! May I ask what OS Build number you are running? Did you download resnet50 from ONNX model zoo?

**Comment by donaparker01** [comment] 2019-06-12 23:07
Hi @ryanlai2 my OS Build # is 10.0.16299 Build 16299, and yes, I downloaded it from the onnx model zoo.

**Comment by ryanlai2** [comment] 2019-06-12 23:18
Hi @donaparker01 , if you update your OS Build # to 10.0.17763 or higher then it should work :) You can find our release notes here: https://docs.microsoft.com/en-us/windows/ai/windows-ml/release-notes

**Comment by LPBourret** [comment] 2019-09-11 18:25
closing, feel free to reopen if the issue is not fixed

**Closed by LPBourret** 2019-09-11 18:25 UTC
